### ISSUE TITLE
Workshop HOL does not match the workshop name

### ISSUE THREAD

**Issue by DivineOps** [Microsoft/MCW-Lift-and-shift-Azure-Resource-Manager#1]
This workshop's hands on lab should _not_ be called Lift & Shift. It would be more appropriate to call it Azure Resource Manager template deployment, or ARM templates and DSC. 

Our recommended Lift & Shift / cloud migration tool is Azure Site Recovery (ASR). While the whiteboarding session covers ASR  as one of the options, the lab doesn't even mention it. This means that people hoping to learn more about Lift & Shift with ASR will not get the expected content. 

It would be more appropriate to use the HOL from the business continuity workshop as a Lift & Shift HOL https://github.com/Microsoft/MCW-Business-Continuity-and-Disaster-Recovery

**Comment by DawnmarieDesJardins** [comment]
Addressed and corrected in June 2018 update.  Thank you!
