### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Lift-and-shift-Azure-Resource-Manager#24]
WDS Student guide:  Lines 139 (https://procurement) & 178 (https://AskHR) - present as links, but don't take students anywhere.

WDS Trainer guide:  Lines 259, 209, 838, 914 & 1220 - same as above.

My guess is those are intentionally fake links for the WDS but, is there a way to format them to be typed in, not as a hyperlink that looks broken?

**Comment by DawnmarieDesJardins** [comment]
Hi Michael, have you had a chance to check on the above for me?  There's also a pull request that came in that says there's a step missing in the August test/fix in the step-by-step lab.  Please review and let me know.  Dawnmarie

**Comment by mwasham** [comment]
Updated - and closed the PR (wasn't valid)
