### ISSUE TITLE
DSC Scripts

### ISSUE THREAD

**Issue by milazzom** [Microsoft/MCW-Lift-and-shift-Azure-Resource-Manager#29]
The DSC scripts in the final scripts archive are mostly commented out and will not achieve the desired result in the HOL.  Also, there are references to CloudShopSQL.ps1 and CloudShopWeb.ps1 and those files do not exist in the project.

**Comment by DawnmarieDesJardins** [comment]
Hi Michael M.
Our author (another Michael) said you'll find what you're looking for in the Before the HOL document of the workshop.  There's a URL in there to download exercise files.  Closing this issue, please feel free to reopen it if this does not solve the problem.
