### ISSUE TITLE
Code is missing in Exercise 5 -> Task 1 -> Step 1 & 2

### ISSUE THREAD

**Issue by PraveenAnil** [Microsoft/MCW-Lift-and-shift-Azure-Resource-Manager#31]
In Exercise 5 > Task 1 > Step 1, while adding the variables to the end of the variables section we need to add one more variable i.e:
    "StorageAccountPrefix": [
      "a",
      "g",
      "m",
      "s",
      "y"
     ]
In Exercise 5 > Task 1 > Step 2, while adding the parameters to the end of the parameters section we need to add one more parameter i.e:
    "newStorageAccountSuffix": {
      "type": "string",
      "metadata": {
        "description": "prefix for storage account"
      }
    }

**Comment by paulopsgility** [comment]
No longer necessary after moving to managed disks.
