### ISSUE TITLE
update server generation

### ISSUE THREAD

**Issue by beber-msft** [Microsoft/MCW-Lift-and-shift-Azure-Resource-Manager#6]
personally I would put the VM on ds2v3 and not ds2v2 for a better performance ratio.

**Comment by jtuliani** [comment]
Updated in june-2108-update branch to suggest either DS2_v2 or D2S_v3 for Web tier, and DS3_v2 or D4S_v3 for the SQL tier. Wanted to keep the v2 option as v3 is not available in many regions, but good idea to flag the existence of v3 as it's a better choice where available.
