### ISSUE TITLE
Note: At the time of this writing, the Azure Database Assistant service is in preview and does not support targeting SQL Server, just SQL Database.

### ISSUE THREAD

**Issue by beber-msft** [Microsoft/MCW-Lift-and-shift-Azure-Resource-Manager#7]
It is now GA:
https://blogs.msdn.microsoft.com/datamigration/2018/05/07/announcing-general-availability-of-the-azure-database-migration-service/

**Comment by mwasham** [comment]
Already addressed in the June update
